<?php

namespace Madrivo\WarmerBundle\Entity;

/**
 * SmsListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsListRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLastUnreadMessageByNumber($number)
	{
		$query = $this->getEntityManager()
			->createQuery('SELECT s FROM MadrivoWarmerBundle:SmsList s WHERE s.numberTo = :to AND s.parsed = :parsed ORDER BY s.id DESC')
			->setParameter("to", $number)
			->setParameter("parsed", 0);
		
		return $query->getOneOrNullResult();
	}
}
