<?php

namespace Madrivo\WarmerBundle\Entity;

/**
 * SmsListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsListRepository extends \Doctrine\ORM\EntityRepository
{
}
